### ISSUE TITLE
Filling empty bytes in C-structs.

### ISSUE THREAD

**Issue by Iipal** [ely-uf/newtype_c#1]
How necessary is to fill the "empty" space in structs in C when, for example, we call `newtype` for `uint8_t` and get 2 bytes of "empty" memory ?
```C
newtype(8_int_t, uint8_t);
````

If it's really have a sense i re-created `newtype` with filling the empty bytes, but for what ... ? Do you have answer on my question ?
```C
# include <stddef.h>

# define newtype(_name, _type) { \
    const size_t _type_sizeof_padding = 4 - (sizeof(_type) % 4); \
    if (4 & _type_sizeof_padding) \
        typedef struct _name { _type val; } _name; \
    else \
        typedef struct _name {_type val; char padding[_type_sizeof_padding];} _name; }
```

**Comment by ely-uf** [comment]
@Iipal I am not quite sure what do you mean.
If you mean padding, I don't see the point of it in here.

Padding makes sense when we have **more than one** element in the struct and we want to improve performance of struct member access. Apart from performance, there also exist alignment rules for several target platforms.

To say more, this sort of `if` conditions is not quite possible on a preprocessor level.

**Comment by Iipal** [comment]
@ely-uf I got u, thanks. But what you mean in "this sort of `if` conditions is not quite possible on a preprocessor level." ?  If `if` conditions not in preprocessor level, so then on which one level is this conditions in `define`s ?
